export const CACHE_TIME:number = 30000;


export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;


export const TEST = 'TEST';
export type TEST = typeof TEST;

export const GET_PROJECT_LIST = 'GET_PROJECT_LIST';
export type GET_PROJECT_LIST = typeof GET_PROJECT_LIST;


export const SET_PROJECT_LIST = 'SET_PROJECT_LIST';
export type SET_PROJECT_LIST = typeof SET_PROJECT_LIST;


export const LOGIN = 'LOGIN';
export type LOGIN = typeof LOGIN;



export const SET_USER_INFO = 'SET_USER_INFO';
export type SET_USER_INFO = typeof SET_USER_INFO;



// work



export const GET_ERROR_ALL_DATA = 'GET_ERROR_ALL_DATA';
export type GET_ERROR_ALL_DATA = typeof GET_ERROR_ALL_DATA;

export const GET_ERROR_CHART_DATA = 'GET_ERROR_CHART_DATA';
export type GET_ERROR_CHART_DATA = typeof GET_ERROR_CHART_DATA;
export const SET_ERROR_CHART_DATA = 'SET_ERROR_CHART_DATA';
export type SET_ERROR_CHART_DATA = typeof SET_ERROR_CHART_DATA;

export const GET_ERROR_LIST_DATA = 'GET_ERROR_LIST_DATA';
export type GET_ERROR_LIST_DATA = typeof GET_ERROR_LIST_DATA;
export const SET_ERROR_LIST_DATA = 'SET_ERROR_LIST_DATA';
export type SET_ERROR_LIST_DATA = typeof SET_ERROR_LIST_DATA;

export const CHANGE_APPOINTER = 'CHANGE_APPOINTER';
export type CHANGE_APPOINTER = typeof CHANGE_APPOINTER;

export const CHANGE_ERROR_STATUS = 'CHANGE_ERROR_STATUS';
export type CHANGE_ERROR_STATUS = typeof CHANGE_ERROR_STATUS;

export const ADD_ERROR_REMARK = 'ADD_ERROR_REMARK';
export type ADD_ERROR_REMARK = typeof ADD_ERROR_REMARK;
export const UPDATE_ERROR_REMARK = 'UPDATE_ERROR_REMARK';
export type UPDATE_ERROR_REMARK = typeof UPDATE_ERROR_REMARK;
export const DELETE_ERROR_REMARK = 'DELETE_ERROR_REMARK';
export type DELETE_ERROR_REMARK = typeof DELETE_ERROR_REMARK;

